# Generated by Django 5.2.3 on 2025-06-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FireballEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("energy", models.FloatField(blank=True, null=True)),
                ("impact_e", models.FloatField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("alt", models.FloatField(blank=True, null=True)),
                ("vel", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date", "lat", "lon")},
            },
        ),
    ]
